"""empty message

Revision ID: 19133799f06a
Revises: 39453fbd1bb0
Create Date: 2020-11-09 15:24:33.780308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19133799f06a'
down_revision = '39453fbd1bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_job', sa.Column('endtime', sa.Time(), nullable=True))
    op.add_column('special_job', sa.Column('starttime', sa.Time(), nullable=True))
    op.drop_column('special_job', 'astarttime')
    op.drop_column('special_job', 'aendtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_job', sa.Column('aendtime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('special_job', sa.Column('astarttime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('special_job', 'starttime')
    op.drop_column('special_job', 'endtime')
    # ### end Alembic commands ###
