"""empty message

Revision ID: 36702c7ec827
Revises: feeb585dd701
Create Date: 2020-11-17 13:24:41.756514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36702c7ec827'
down_revision = 'feeb585dd701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dayjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('jobname', sa.String(length=20), nullable=False),
    sa.Column('starttime', sa.Time(), nullable=True),
    sa.Column('endtime', sa.Time(), nullable=True),
    sa.Column('priority', sa.String(length=3), nullable=True),
    sa.Column('required_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobname')
    )
    op.create_table('jobtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dayname', sa.String(length=5), nullable=False),
    sa.Column('starttime', sa.Time(), nullable=True),
    sa.Column('endtime', sa.Time(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('job', sa.Column('everyday', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('monthday', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('weekday', sa.Boolean(), nullable=True))
    op.drop_constraint('job_jobname_key', 'job', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('job_jobname_key', 'job', ['jobname'])
    op.drop_column('job', 'weekday')
    op.drop_column('job', 'monthday')
    op.drop_column('job', 'everyday')
    op.drop_table('jobtime')
    op.drop_table('dayjob')
    # ### end Alembic commands ###
