"""empty message

Revision ID: 39453fbd1bb0
Revises: 78530a317fc8
Create Date: 2020-11-09 15:24:02.237651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39453fbd1bb0'
down_revision = '78530a317fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_job', sa.Column('aendtime', sa.Time(), nullable=True))
    op.add_column('special_job', sa.Column('astarttime', sa.Time(), nullable=True))
    op.drop_column('special_job', 'endtime')
    op.drop_column('special_job', 'starttime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special_job', sa.Column('starttime', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('special_job', sa.Column('endtime', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('special_job', 'astarttime')
    op.drop_column('special_job', 'aendtime')
    # ### end Alembic commands ###
