"""empty message

Revision ID: 4128124e84b5
Revises: 499bcf00d9a0
Create Date: 2020-11-05 11:06:53.032709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4128124e84b5'
down_revision = '499bcf00d9a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_opentime', sa.Time(), nullable=True),
    sa.Column('store_closetime', sa.Time(), nullable=True),
    sa.Column('job_divtime', sa.Time(), nullable=True),
    sa.Column('min_shift', sa.Time(), nullable=True),
    sa.Column('restnd_mint', sa.Time(), nullable=True),
    sa.Column('resttime', sa.Time(), nullable=True),
    sa.Column('restname', sa.String(), nullable=True),
    sa.Column('priorty_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_config')
    # ### end Alembic commands ###
