"""empty message

Revision ID: 78530a317fc8
Revises: 9c951250d8fb
Create Date: 2020-11-09 15:16:51.326036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78530a317fc8'
down_revision = '9c951250d8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('Fri', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Friendtime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Fristarttime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Mon', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Monendtime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Monstarttime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Sat', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Satendtime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Satstarttime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Sun', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Sunendtime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Sunstarttime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Thu', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Thuendtime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Thustarttime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Tue', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Tueendtime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Tuestarttime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Wed', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Wedendtime', sa.Time(), nullable=True))
    op.add_column('worker', sa.Column('Wedstarttime', sa.Time(), nullable=True))
    op.drop_column('worker', 'satendtime')
    op.drop_column('worker', 'wedstarttime')
    op.drop_column('worker', 'sunendtime')
    op.drop_column('worker', 'wedendtime')
    op.drop_column('worker', 'mon')
    op.drop_column('worker', 'fri')
    op.drop_column('worker', 'thuendtime')
    op.drop_column('worker', 'satstarttime')
    op.drop_column('worker', 'sun')
    op.drop_column('worker', 'fristarttime')
    op.drop_column('worker', 'wed')
    op.drop_column('worker', 'sat')
    op.drop_column('worker', 'thu')
    op.drop_column('worker', 'tueendtime')
    op.drop_column('worker', 'monendtime')
    op.drop_column('worker', 'friendtime')
    op.drop_column('worker', 'monstarttime')
    op.drop_column('worker', 'sunstarttime')
    op.drop_column('worker', 'thustarttime')
    op.drop_column('worker', 'tuestarttime')
    op.drop_column('worker', 'tue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('tue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('tuestarttime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('thustarttime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('sunstarttime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('monstarttime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('friendtime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('monendtime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('tueendtime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('thu', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('sat', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('wed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('fristarttime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('sun', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('satstarttime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('thuendtime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('fri', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('mon', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('wedendtime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('sunendtime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('wedstarttime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('satendtime', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('worker', 'Wedstarttime')
    op.drop_column('worker', 'Wedendtime')
    op.drop_column('worker', 'Wed')
    op.drop_column('worker', 'Tuestarttime')
    op.drop_column('worker', 'Tueendtime')
    op.drop_column('worker', 'Tue')
    op.drop_column('worker', 'Thustarttime')
    op.drop_column('worker', 'Thuendtime')
    op.drop_column('worker', 'Thu')
    op.drop_column('worker', 'Sunstarttime')
    op.drop_column('worker', 'Sunendtime')
    op.drop_column('worker', 'Sun')
    op.drop_column('worker', 'Satstarttime')
    op.drop_column('worker', 'Satendtime')
    op.drop_column('worker', 'Sat')
    op.drop_column('worker', 'Monstarttime')
    op.drop_column('worker', 'Monendtime')
    op.drop_column('worker', 'Mon')
    op.drop_column('worker', 'Fristarttime')
    op.drop_column('worker', 'Friendtime')
    op.drop_column('worker', 'Fri')
    # ### end Alembic commands ###
