"""empty message

Revision ID: 7c7419579e84
Revises: 7e8dd8f5b1ef
Create Date: 2020-11-26 14:32:42.760275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c7419579e84'
down_revision = '7e8dd8f5b1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobtime')
    op.drop_constraint('dayjob_job_id_fkey', 'dayjob', type_='foreignkey')
    op.drop_column('dayjob', 'job_id')
    op.drop_column('job', 'monthday')
    op.drop_column('job', 'weekday')
    op.drop_column('job', 'everyday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('everyday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('weekday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('monthday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dayjob', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dayjob_job_id_fkey', 'dayjob', 'job', ['job_id'], ['id'])
    op.create_table('jobtime',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dayname', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('starttime', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('endtime', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='jobtime_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='jobtime_pkey')
    )
    # ### end Alembic commands ###
