"""empty message

Revision ID: 7e8dd8f5b1ef
Revises: fe633069e33e
Create Date: 2020-11-17 14:16:32.528727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8dd8f5b1ef'
down_revision = 'fe633069e33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('be_indispensable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'be_indispensable')
    # ### end Alembic commands ###
