"""empty message

Revision ID: 9c43f5a897fd
Revises: 7c7419579e84
Create Date: 2020-11-26 14:36:02.277044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c43f5a897fd'
down_revision = '7c7419579e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('priority2', sa.String(length=3), nullable=True))
    op.drop_column('job', 'priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('priority', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.drop_column('job', 'priority2')
    # ### end Alembic commands ###
