"""empty message

Revision ID: bc22c2b3ce63
Revises: c433ef14be48
Create Date: 2020-11-27 15:36:59.252266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc22c2b3ce63'
down_revision = 'c433ef14be48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dayworker', sa.Column('position', sa.String(length=20), nullable=True))
    op.add_column('worker', sa.Column('position', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'position')
    op.drop_column('dayworker', 'position')
    # ### end Alembic commands ###
