"""empty message

Revision ID: c433ef14be48
Revises: dedc196b8469
Create Date: 2020-11-26 15:23:37.114111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c433ef14be48'
down_revision = 'dedc196b8469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dayjob', sa.Column('be_indispensable', sa.Boolean(), nullable=True))
    op.add_column('dayjob', sa.Column('employee_priority', sa.String(length=3), nullable=True))
    op.add_column('dayjob', sa.Column('helper_priority', sa.String(length=3), nullable=True))
    op.add_column('dayjob', sa.Column('one_date', sa.DateTime(), nullable=False))
    op.add_column('dayjob', sa.Column('parttime_priority', sa.String(length=3), nullable=True))
    op.add_column('dayjob', sa.Column('weight', sa.String(length=3), nullable=True))
    op.drop_constraint('dayjob_jobname_key', 'dayjob', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('dayjob_jobname_key', 'dayjob', ['jobname'])
    op.drop_column('dayjob', 'weight')
    op.drop_column('dayjob', 'parttime_priority')
    op.drop_column('dayjob', 'one_date')
    op.drop_column('dayjob', 'helper_priority')
    op.drop_column('dayjob', 'employee_priority')
    op.drop_column('dayjob', 'be_indispensable')
    # ### end Alembic commands ###
