"""empty message

Revision ID: dedc196b8469
Revises: bf04a865d47b
Create Date: 2020-11-26 14:40:58.752955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedc196b8469'
down_revision = 'bf04a865d47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('employee_priority', sa.String(length=3), nullable=True))
    op.add_column('job', sa.Column('helper_priority', sa.String(length=3), nullable=True))
    op.add_column('job', sa.Column('parttime_priority', sa.String(length=3), nullable=True))
    op.add_column('job', sa.Column('priority', sa.String(length=3), nullable=True))
    op.add_column('job', sa.Column('weight', sa.String(length=3), nullable=True))
    op.drop_column('job', 'weight2')
    op.drop_column('job', 'employee_priority2')
    op.drop_column('job', 'parttime_priority2')
    op.drop_column('job', 'helper_priority2')
    op.drop_column('job', 'priority3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('priority3', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('helper_priority2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('parttime_priority2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('employee_priority2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('weight2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('job', 'weight')
    op.drop_column('job', 'priority')
    op.drop_column('job', 'parttime_priority')
    op.drop_column('job', 'helper_priority')
    op.drop_column('job', 'employee_priority')
    # ### end Alembic commands ###
