"""empty message

Revision ID: ec38fcc474a9
Revises: 19133799f06a
Create Date: 2020-11-09 17:17:50.304686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec38fcc474a9'
down_revision = '19133799f06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dayworker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_date', sa.DateTime(), nullable=False),
    sa.Column('workername', sa.String(length=20), nullable=False),
    sa.Column('starttime', sa.Time(), nullable=True),
    sa.Column('endtime', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dayworker')
    # ### end Alembic commands ###
