"""empty message

Revision ID: f17d3ae03168
Revises: 4128124e84b5
Create Date: 2020-11-06 11:41:44.325462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17d3ae03168'
down_revision = '4128124e84b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('Fri', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Mon', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Sat', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Sun', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Thu', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Tue', sa.Boolean(), nullable=True))
    op.add_column('worker', sa.Column('Wed', sa.Boolean(), nullable=True))
    op.drop_column('worker', 'Saturday')
    op.drop_column('worker', 'Wednesday')
    op.drop_column('worker', 'Friday')
    op.drop_column('worker', 'Monday')
    op.drop_column('worker', 'Thursday')
    op.drop_column('worker', 'Tuesday')
    op.drop_column('worker', 'Sunday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('Sunday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('Tuesday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('Thursday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('Monday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('Friday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('Wednesday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('Saturday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('worker', 'Wed')
    op.drop_column('worker', 'Tue')
    op.drop_column('worker', 'Thu')
    op.drop_column('worker', 'Sun')
    op.drop_column('worker', 'Sat')
    op.drop_column('worker', 'Mon')
    op.drop_column('worker', 'Fri')
    # ### end Alembic commands ###
