"""empty message

Revision ID: fe633069e33e
Revises: 36702c7ec827
Create Date: 2020-11-17 14:13:08.035819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe633069e33e'
down_revision = '36702c7ec827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('employee_priority', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('helper_priority', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('parttime_priority', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'weight')
    op.drop_column('job', 'parttime_priority')
    op.drop_column('job', 'helper_priority')
    op.drop_column('job', 'employee_priority')
    # ### end Alembic commands ###
